# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQ7AScIBtGN6H6FVJyzCpm1jokO73KSs
"""

import pandas as pd

# 1. Carga del pergamino secreto
df = pd.read_csv('misiones_limpias.csv')
df

# Ver la descripción estadística
descripcion = df.describe()
print(descripcion)

# Mostrar la media y desviación estándar de Nivel_Chakra específicamente
print("Media de Chakra:", df['Nivel_Chakra'].mean())
print("Desviación Estándar:", df['Nivel_Chakra'].std())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
# Usamos la columna Nivel_Chakra de nuestro DataFrame
sns.boxplot(y=df['Nivel_Chakra'], color='orange')
plt.title('Distribución de Nivel de Chakra de los Ninjas')
plt.ylabel('Nivel de Chakra')
plt.show()

# Calcular la media y la desviación estándar
media_chakra = df['Nivel_Chakra'].mean()
std_chakra = df['Nivel_Chakra'].std()

# Calcular el Z-Score
df['Z_Score'] = (df['Nivel_Chakra'] - media_chakra) / std_chakra

# Filtrar outliers (Z-Score > 3 o < -3)
infiltrados = df[df['Z_Score'].abs() > 3]
print("--- Posibles Infiltrados (Z-Score extremo) ---")
print(infiltrados.head())

# Ninjas con Chakra Negativo
chakra_negativo = df[df['Nivel_Chakra'] < 0]
print("--- Ninjas con Chakra Negativo ---")
print(chakra_negativo.head())

# Ninjas de la Aldea Desconocida
aldea_desconocida = df[df['Aldea'] == 'Desconocida']
print("--- Ninjas de Aldea Desconocida ---")
print(aldea_desconocida.head())

# Super Ninjas (Z-Score entre 2 y 3 o entre -2 y -3)
super_ninjas = df[(df['Z_Score'].abs() > 2) & (df['Z_Score'].abs() <= 3)]
print("--- Super Ninjas (Fuertes, pero no traidores) ---")
print(super_ninjas.head())

# Mostrar todos los datos de los sospechosos de Z-Score > 3 y de la Aldea Desconocida
# Veremos si coinciden
sospechosos = pd.concat([infiltrados, aldea_desconocida]).drop_duplicates()
print("--- Todos los Sospechosos ---")
print(sospechosos)

# Para ver si el infiltrado de chakra alto coincide con aldea desconocida:
coincidencia = pd.merge(infiltrados, aldea_desconocida, on='ID', how='inner')
print("¿Coinciden los infiltrados con la aldea desconocida?")
print(coincidencia)