# -*- coding: utf-8 -*-
"""Ut4_Practica1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP9aqgik4w5VqCyiUbwtyFRetHl7eH2l
"""

import pandas as pd

# 1. Carga del pergamino secreto
df = pd.read_csv('registros_misiones.csv')
df

# --- SECCIÓN 1: LIMPIEZA DE DATOS ---

def limpiar_registro(df):
    # Reto 1: Elimina filas duplicadas.
    df = df.drop_duplicates()

    # Reto 2: Estandariza la columna 'aldea' (quitar espacios, solventar mayúsculas/minúsculas).
    df["aldea"] = df["aldea"].str.lower().str.strip()

    # Reto 3: Si 'nin_id' es nulo y la 'aldea' es 'Kiri', rellena con 'Ninja de la Niebla Anonimo'.
    df.loc[df['nin_id'].isna() & (df['aldea'] == 'Kiri'), 'nin_id'] = 'Ninja de la Niebla Anonimo'

    # Reto 4: Convierte 'ts' a datetime.
    df['ts'] = pd.to_datetime(df['ts'], errors='coerce')

    # Reto 5: Filtra o corrige niveles de chakra imposibles (<= 0 o > 100.000).
    df = df[(df['chakra'] > 0) & (df['chakra'] <= 100000)]

    # Reto 6: Renombra las columnas:
    df = df.rename(columns={
        'id_reg': 'ID',
        'ts': 'Fecha',
        'nin_id': 'Ninja',
        'status': 'Estado',
        'desc': 'Descripcion'
    })
    # Tu código aquí
    return df

# --- SECCIÓN 2: BÚSQUEDA Y CONSULTAS ---

def realizar_consultas(df):

    # Reto 7: Busca descripciones con las palabras 'espía', 'sospechoso' o 'enemigo'.
    resultado1 = df[df['Descripcion'].str.contains('espía', case=False, na=False)]

    resultado2 = df[df['Descripcion'].str.contains('sospechoso', case=False, na=False)]

    resultado3 = df[df['Descripcion'].str.contains('enemigo', case=False, na=False)]
    print("\n--- Reto 7 ---")
    print(resultado1,resultado2,resultado3)

    # Reto 8: Filtra ninjas de la 'Aldea de la Lluvia' (Amegakure) con chakra > 5000 y rango != 'D'.
    reto8 = df[
        (df['aldea'] == 'Amegakure') &
        (df['chakra'] > 5000) &
        (df['rango'] != 'D')
    ]
    print("\n--- Reto 8 ---")
    print(reto8)
    # Reto 9: Encuentra los accesos ocurridos de madrugada (entre las 23:00 y las 05:00).
    horas = df['Fecha'].dt.hour
    reto9 = df[(horas >= 23) | (horas <= 5)]
    print("\n--- Reto 9 ---")
    print(reto9)
    # Reto 10: Obtén el Top 5 ninjas con más chakra de cada aldea.
    reto10 = (
        df.sort_values('chakra', ascending=False)
        .groupby('aldea')
        .head(5)
        .sort_values('aldea')
    )
    print("\n--- Reto 10 ---")
    print(reto10)
    # Reto 11: Lista misiones de ninjas que NO pertenecen a la alianza (Konoha, Suna, Kumo).
    # Reto 12: Cuenta cuántas misiones de estado 'Fallo' hay por cada aldea.

    # Tu código aquí
    pass

# --- EJECUCIÓN DEL PROTOCOLO ANBU ---
print("Iniciando Rastreo de Chakra de Rodrigo Bueno...")
df_limpio = limpiar_registro(df)
realizar_consultas(df_limpio)
df_limpio.to_csv('misiones_limpias_Rodrigo Bueno.csv', index=False)